# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 672b1dbc3ecfbed5bee9c1a750f7a2b45ebd97571f3245fb3b53d588746115088913291e8646269a02c6efb39f507590e18c4bb2c7adef4a9cd4b2543e30c325

test:
  secret_key_base: c3efe325bbcd9a1718d2659a5ba1c2086e4d3c54e7c636960a51be6f53b79d86ca86ac20be7d32dfa9b83f7b975d30f6acd0b7e631e38564ab25975350426be0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
